# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PagieExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PagieExample
  pod 'Pagie', :path => "../Pagie"

  target 'PagieExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PagieExampleUITests' do
    # Pods for testing
  end

end
